### PR TITLE
fix: add url validation for custom images

### LINKED ISSUE #59: Add validation to image_name in notebook server creation to prevent or strip leading "http[s]://"
When creating a notebook server you can enter an image name that has a leading `http[s]://`, but this will never work (the name used here is a docker image, eg: `[repo/]imagename:tag`).  The frontend can validate this input and do one of:
* strip leading `http[s]://` from any image name without the user knowing it had to be done (preferable unless there's a use case that ever needs the leading http)
* warn the user when filling out he form (or reject outright) that http is not accepted (do this if we don't think we can just safely always strip)

### PR DESCRIPTION
**Pull request by jumana-s**
Resolves #59

### CODE REVIEW

File: frontend/src/app/resource-form/form-image/form-image.component.ts [hunk 1]
```diff
@@ -12,24 +19,66 @@ export class FormImageComponent implements OnInit {
...
+      return this.translate.instant("formImage.errorHttp", {
+        http: `${urlBeginning}`
+      });
+    }
+  }
+
+  private urlValidator(): ValidatorFn {
+    return (control: AbstractControl): {[key: string]: any} => {
+      const valid = control.value.search(/^http[s]?:\/\//i);
+      return valid != -1 ? {validUrl: true} : null;
```
Comment (wg102) [inline frontend/src/app/resource-form/form-image/form-image.component.ts:81]: Why not use RegExp directly instead? (bis)

File: frontend/src/app/resource-form/form-image/form-image.component.ts [hunk 2]
```diff
@@ -12,24 +19,66 @@ export class FormImageComponent implements OnInit {
...
     return displayName;
   }
+
+  urlValidation(): void {
+    const url = this.parentForm.get("customImage");
+
+    if (url.hasError("validUrl")) {
+      let urlBeginning;
+
+      if (url.value.search(/http:\/\//i) != -1) {
```
Comment (wg102) [inline frontend/src/app/resource-form/form-image/form-image.component.ts:66]: Why not use RegExp directly?

**Review by wg102 — CHANGES_REQUESTED** [review]
DS_Store file is something specific to MacOS, and should not be added to the project.

**Review by wg102 — APPROVED** [review]
