### PR TITLE
Fix limit local dev deployment

### LINKED ISSUE #11: Limit local dev deployments to localhost
App deploys statically to `0.0.0.0`. This should be limited for local development setups so the developer's permission set is not given a public endpoint.

### PR DESCRIPTION
**Pull request by wg102**
Resolves #11

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -76,6 +77,7 @@ func main() {
 	flag.StringVar(&userIDHeader, "userid-header", "kubeflow-userid", "header in the request which identifies the incoming user")
 	flag.StringVar(&spawnerConfigPath, "spawner-config", "/etc/config/spawner_ui_config.yaml", "path to the spawner configuration file")
 	flag.StringVar(&staticDirectory, "static-dir", "static/", "path to the static assets")
+	flag.StringVar(&listenAddr, "listen-addr", "127.0.0.1:5000", "server listen address")
```
Comment (brendangadd) [inline main.go:80]: Can we do the whole configuration fallback right here (with an extra functions)? Like...

```go
// With this function defined...
func lookupEnv(name string, defaultValue string) string {
	if value, isSet := os.LookupEnv(name); isSet {
		return value
	}
	return defaultValue
}
// You can do...
flag.StringVar(&listenAddress, "listen-address",
	lookupEnv("LISTEN_ADDRESS", "127.0.0.1:5000"),
	"host and port to bind")
```
